version: "3.8"

services:

  localstack:
    container_name: "localstack"

  tornado-api:
    container_name: "tornado-api"
    image: doofi/tornado-api:latest
    network_mode: bridge
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - QUEUE_URL=http://localhost:4566/000000000000/notices
      - QUEUE_REGION=us-east-1

  tornado-worker:
    image: foo/bar
