// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns HTTP 200 upon and only upon a successfully completed request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Returns a indicator of health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Response"
                        }
                    }
                }
            }
        },
        "/notices": {
            "post": {
                "description": "Parses JSON request body into a notice to be enqueued at AWS SQS for future consumption",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notices"
                ],
                "summary": "Enqueues a new finding notice",
                "parameters": [
                    {
                        "description": "Notice to enqueue",
                        "name": "notice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Notice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.EnqueuedMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.EnqueuedMessage": {
            "type": "object",
            "properties": {
                "attributes_md5": {
                    "type": "string",
                    "example": "e64461b4cb51a781f7d35414369a7bfc"
                },
                "body_md5": {
                    "type": "string",
                    "example": "f27eca4f499f59e0328f3f4ae35a4a1b"
                },
                "id": {
                    "type": "string",
                    "example": "69069c03-8720-e75a-f386-3ca5b3d56801"
                },
                "sequence": {
                    "type": "string",
                    "example": "null"
                },
                "system_attributes_md5": {
                    "type": "string",
                    "example": "null"
                }
            }
        },
        "main.Notice": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string",
                    "example": "C05002EAE"
                },
                "finding": {
                    "type": "string",
                    "example": "ThreatPurpose:ResourceTypeAffected/ThreatFamilyName.DetectionMechanism!Artifact"
                },
                "subject": {
                    "type": "string",
                    "example": "An EC2 instance is behaving in a manner indicating it is being used to perform a Denial of Service (DoS) attack using the TCP protocol."
                }
            }
        },
        "main.Response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "My generic user friendly message about response from some request"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Tornado API",
	Description:      "API to enqueue findings with AWS SQS",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
